<?xml version="1.0" encoding="utf-8"?><Database Name="QL_TourDuLich" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=MSI;Initial Catalog=QL_TourDuLich;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QL_TourDuLichConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DIEMTHAMQUAN" Member="DIEMTHAMQUANs">
    <Type Name="DIEMTHAMQUAN">
      <Column Name="MaDiaDanh" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDiaDanh" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Diachi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HinhAnh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DacTrung" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DIEMTHAMQUAN_TOUR" Member="TOURs" ThisKey="MaDiaDanh" OtherKey="MaDiaDanh" Type="TOUR" />
    </Type>
  </Table>
  <Table Name="dbo.VE" Member="VEs">
    <Type Name="VE">
      <Column Name="MaVe" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayBook" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ChiPhiDauNguoi" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MaTour" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="KHACHHANG_VE" Member="KHACHHANG" ThisKey="MaKH" OtherKey="MaKH" Type="KHACHHANG" IsForeignKey="true" />
      <Association Name="TOUR_VE" Member="TOUR" ThisKey="MaTour" OtherKey="MaTour" Type="TOUR" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MaKH" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgSinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Phai" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CCCD" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Association Name="KHACHHANG_VE" Member="VEs" ThisKey="MaKH" OtherKey="MaKH" Type="VE" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MaNV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgSinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Phai" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Association Name="NHANVIEN_TOUR" Member="TOURs" ThisKey="MaNV" OtherKey="MaHDV" Type="TOUR" />
    </Type>
  </Table>
  <Table Name="dbo.TOUR" Member="TOURs">
    <Type Name="TOUR">
      <Column Name="MaTour" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayBD" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NgayKT" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DiemXuatPhat" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ChiPhiDauNguoi" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SoLuongCon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuongBook" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaHDV" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaDiaDanh" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TongTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="TOUR_VE" Member="VEs" ThisKey="MaTour" OtherKey="MaTour" Type="VE" />
      <Association Name="DIEMTHAMQUAN_TOUR" Member="DIEMTHAMQUAN" ThisKey="MaDiaDanh" OtherKey="MaDiaDanh" Type="DIEMTHAMQUAN" IsForeignKey="true" />
      <Association Name="NHANVIEN_TOUR" Member="NHANVIEN" ThisKey="MaHDV" OtherKey="MaNV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
</Database>